### ISSUE TITLE
ValueError: Unknown format code 'd' for object of type 'str'

### ISSUE THREAD

**Issue by lhchinelatto** [benedictus79/Hotm4rtei#22]
Hi. I'm getting the following error when trying to run your script:

```
Cursos disponíveis:
1. reumaflix
Escolha um curso pelo número: 1
reumaflix:   0%|                                                                                 | 0/4 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\luish\github\Hotm4rtei\main.py", line 126, in <module>
    redirect_club_hotmart(course_name, token)
  File "C:\Users\luish\github\Hotm4rtei\main.py", line 122, in redirect_club_hotmart
    list_modules(course_name, filtered_modules)
  File "C:\Users\luish\github\Hotm4rtei\main.py", line 106, in list_modules
    process_module(module_data, main_course_folder, course_name)
  File "C:\Users\luish\github\Hotm4rtei\main.py", line 96, in process_module
    process_lessons_details(lessons, course_name)
  File "C:\Users\luish\github\Hotm4rtei\main.py", line 87, in process_lessons_details
    download_video(processed_lessons, hotmartsession)
  File "C:\Users\luish\github\Hotm4rtei\download.py", line 93, in download_video
    process_webinar(webinar_folder, lesson_name, lesson_data['webinar'], session)
  File "C:\Users\luish\github\Hotm4rtei\download.py", line 55, in process_webinar
    webinar_folder = concat_path(webinar_folder, f'{index:03d} - {webinar_title}.mp4')
                                                   ^^^^^^^^^^^
ValueError: Unknown format code 'd' for object of type 'str'
PS C:\Users\luish\github\Hotm4rtei>
```

I've installed all the requirements and followed all the instructions. It'd be awesome if I could get any help with the issue.

Thanks you!

**Comment by camagada** [comment]
I was having the same problem.

This happened when I clicked directly on main.py (via mouse click).
opening the terminal and typing main.py solved the problem.

google translate
