### ISSUE TITLE
It just gets stuck on 0%

### ISSUE THREAD

**Issue by doiiido** [benedictus79/Hotm4rtei#32]
Tem alguma flag de debug?
O código travou assim que selecionei o curso em 0%, sem erros reportados...

Inicialmente estava por SSH em uma VM Ubuntu 22.04 rodando no Hyper-V com 4vcpu e 4GB de RAM, testei também em uma VM com Ubuntu Desktop 22.04 minimal. Ambos com o mesmo comportamento.
Todos os testes foram realizados com venv.
quando dou ctrl+C:

```
Cursos disponíveis:
1. CursoA
2. CursoB
3. CursoC
4. CursoD
Escolha um curso pelo número: 1
CursoA:   0%|                                                                                                                                                                                 | 0/21 [00:00<?, ?it/s]CursoA:   0%|                                                                                                                                                                                 | 0/26 [03:20<?, ?it/s]
Traceback (most recent call last):
  File "/home/lincoln/Hotm4rtei/main.py", line 134, in <module>
    redirect_club_hotmart(course_name, token)
  File "/home/lincoln/Hotm4rtei/main.py", line 130, in redirect_club_hotmart
    list_modules(course_name, filtered_modules)
  File "/home/lincoln/Hotm4rtei/main.py", line 114, in list_modules
    process_module(module_data, main_course_folder, course_name)
  File "/home/lincoln/Hotm4rtei/main.py", line 100, in process_module
    process_lessons_details(lessons, course_name)
  File "/home/lincoln/Hotm4rtei/main.py", line 91, in process_lessons_details
    download_video(processed_lessons, hotmartsession)
  File "/home/lincoln/Hotm4rtei/download.py", line 125, in download_video
    with ThreadPoolExecutor(max_workers=5) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1537, in _shutdown
    atexit_call()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
```

O CursoA tem mais de 100 vídeos e suponho que o erro seja relacionado à quantidade de objetos a serem baixados...

**Comment by doiiido** [comment]
```
Python 3.10.12
Requirement already satisfied: beautifulsoup4==4.12.2 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (4.12.2)
Requirement already satisfied: Brotli==1.1.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: bs4==0.0.1 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.0.1)
Requirement already satisfied: certifi==2023.11.17 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (2023.11.17)
Requirement already satisfied: charset-normalizer==3.3.2 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (3.3.2)
Requirement already satisfied: colorama==0.4.6 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (0.4.6)
Requirement already satisfied: idna==3.6 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.6)
Requirement already satisfied: mutagen==1.47.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (1.47.0)
Requirement already satisfied: pycryptodomex==3.19.1 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (3.19.1)
Requirement already satisfied: requests==2.31.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2.31.0)
Requirement already satisfied: setuptools==65.5.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (65.5.0)
Requirement already satisfied: soupsieve==2.5 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2.5)
Requirement already satisfied: tqdm==4.66.1 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (4.66.1)
Requirement already satisfied: urllib3==2.1.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (2.1.0)
Requirement already satisfied: websocket-client==1.7.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (1.7.0)
Requirement already satisfied: websockets==12.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (12.0)
Requirement already satisfied: yt-dlp==2023.12.30 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (2023.12.30)

```

**Comment by doiiido** [comment]
A url base do curso é completamente diferente do esperado no programa:
https://hotmart.com/pt-br/club/<nome da empresa>/products/<id>
